INSERT INTO exercises (id, name, muscle_group, zone) VALUES
('u3v4w5x6', 'Abdominal crunch', 'Abdomen', 'Funcional'),
('o5p6q7r8', 'Abductor', 'Glúteo', 'Funcional'),
('k1l2m3n4', 'Aductor', 'Aductores', 'Funcional'),
('e9f1c9a8b3e9', 'Azote de cuerda en sentadilla isometrica', 'Cuádriceps/glúteo/hombro', 'Funcional'),
('hc1a2b38', 'Caminadora', 'Todo el cuerpo', 'Cardio'),
('f1c9a8b3e9', 'Cangrejo codo a la rodilla', 'Abdomen (oblicuos)', 'Funcional'),
('f8a9b2c7', 'Cardio a elegir', 'Todo el cuerpo', 'Cardio'),
('ij1k2l3m', 'Circuito Express', 'Todo el cuerpo', 'Circuito Express'),
('a7b3c6d9', 'Clase de circuito express', 'Todo el cuerpo', 'Circuito Express'),
('w4x5y6z7', 'Clase PE@PF', 'Todo el cuerpo', 'Funcional/Circuito Express'),
('f5g6h7i8', 'Curl de Bicep Predicador', 'Biceps', 'Peso integrado'),
('i9j1k2l3', 'Curl de Biceps', 'Biceps', 'Peso integrado'),
('i2j6k3l7', 'Curl de Bíceps en polea baja', 'Biceps', 'Poleas'),
('g6h7i8j9', 'Curl de Piernas Sentado', 'Femoral', 'Peso integrado'),
('a8b3e9f1c9a8', 'Curl martillo alternado con mancuerna', 'Bicep', 'Funcional'),
('d9e1f5a3', 'Desplante alternado con salto', 'Cuádriceps/glúteo/femoral', 'Funcional'),
('d3e4f5g6', 'Desplante TRX', 'Cuádriceps/glúteo/femoral', 'Funcional'),
('h4e6f8a2', 'Elíptica', 'Todo el cuerpo', 'Cardio'),
('d1c9a8b3e9f1', 'Escaladores', 'Abdomen (oblicuos)', 'Funcional'),
('a4b3e9f1', 'Escaladores cruzados', 'Abdomen (oblicuos)', 'Funcional'),
('c2d3e4f5', 'Extensión de Cuádriceps', 'Cuádriceps', 'Peso integrado'),
('p6q7r8s9', 'Extensión de Espalda', 'Lumbar', 'Peso integrado'),
('s9t1u2v3', 'Extensión de Gemelos', 'Pantorrilla', 'Peso integrado'),
('d2e3f4g5', 'Extensión de Triceps', 'Triceps', 'Peso integrado'),
('n5o6p7q8', 'Extensión de Triceps en Polea', 'Triceps', 'Peso integrado'),
('l2m3n4o5', 'Glúteo', 'Glúteo', 'Funcional'),
('x6y7z8a9', 'Hammer Strength Chest Press', 'Pectoral', 'Peso integrado'),
('b1c2d3e4', 'Hammer Strength incline Chest', 'Pectoral', 'Peso integrado'),
('g1h5i2j6', 'Hammer Strength Incline Chest Press', 'Pectoral', 'Peso integrado'),
('z7a8b9c1', 'Hammer Strength Mts front Pulldown', 'Espalda', 'Peso integrado'),
('v3w4x5y6', 'Hammer strength mts Remo', 'Espalda', 'Peso integrado'),
('t2u3v4w5', 'Hammer strength Shoulder Press', 'Hombros', 'Peso integrado'),
('z8a9b1c2', 'Jalón al Pecho', 'Espalda', 'Peso integrado'),
('c9a8b3e9f1c9', 'Lagartijas', 'Pectoral', 'Funcional'),
('d2a4b3e9', 'Marcha alternada estático', 'Cuádriceps/glúteo', 'Funcional'),
('f1c9a8b3e9f', 'Oruga', 'Abdomen', 'Funcional'),
('b3e9f1c9a8', 'Paso joggie', 'Cuádriceps/glúteo', 'Funcional'),
('jt4u5v6w', 'Plancha con apertura de piernas', 'Abdomen', 'Funcional'),
('r9s1t2u3', 'Plancha con flexión y extensión de codos', 'Abdomen', 'Funcional'),
('b9c3d7e1', 'Plancha con rotación de torso', 'Abdomen', 'Funcional'),
('b3e9f1c9', 'Plancha estatica en Bosú', 'Abdomen', 'Funcional'),
('k3l7m4n8', 'Plancha lateral', 'Abdomen', 'Funcional'),
('h7i8j9k1', 'Prensa de Pierna', 'Cuádriceps/glúteo/femoral', 'Peso integrado'),
('a1b2c3d4', 'Press de Hombro', 'Hombros', 'Peso integrado'),
('e5f6g7h8', 'Press de Pecho', 'Pectoral', 'Peso integrado'),
('m4n5o6p7', 'Press de triceps', 'Triceps', 'Peso integrado'),
('j3k4l5m6', 'Remo en Polea', 'Espalda', 'Peso integrado'),
('q8r9s1t2', 'Remo Sentado', 'Espalda', 'Peso integrado'),
('ig7h8i9j', 'Rotación de torso', 'Abdomen (oblicuos)', 'Funcional'),
('o5p9q2r6', 'Rotación de torso en maquina', 'Abdomen (oblicuos)', 'Peso integrado'),
('d5e6f8a9', 'Saltos rodillas al pecho', 'Cuádriceps/glúteo', 'Funcional'),
('a8b3e9f1c9a8b', 'Sentadilla con Salto rodillas al pecho', 'Cuádriceps/glúteo', 'Funcional'),
('d1c9a8b3e9', 'Sentadilla sobre Bosú', 'Cuádriceps/glúteo/femoral', 'Funcional'),
('y7z8a9b1', 'Sentadilla TRX', 'Cuádriceps/glúteo/femoral', 'Funcional'),
('e9f2a7b4', 'Sentadilla TRX con salto', 'Cuádriceps/glúteo/femoral', 'Funcional'),
('a3b8c1d6', 'Sentadillas', 'Cuádriceps/glúteo/femoral', 'Funcional'),
('ia1b2c3d', 'Talones alternados al glúteo', 'Glúteo/femoral', 'Funcional'),
('b1c5d8e2', 'Tijeras frontales en tapete', 'Abdomen', 'Funcional');
